version: '3'
services:
  backend:
    build: .
    volumes:
      - .:/my-app
    container_name: ga_backend
    ports:
      - ${PORT}:4000
    depends_on:
      - db
  db:
    container_name: ${DB_HOST}
    image: postgres:10.7
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
